import random
from datetime import datetime, timedelta
from typing import List, Dict


def _spread_dates(n: int, days_back: int = 180) -> List[datetime]:
    now = datetime.now()
    return sorted(
        now - timedelta(days=random.randint(0, days_back), hours=random.randint(0, 23))
        for _ in range(n)
    )


_RAW: Dict[str, List[Dict]] = {
    "oral care": [
        {"text": "Switched to neem-based toothpaste 3 months ago and my gums have never felt healthier. No more bleeding when I floss!", "source": "Reddit", "engagement": 312, "country": "India"},
        {"text": "Herbal toothpaste is a game changer. Fresh breath all day without the harsh chemical taste. Completely natural and it actually works.", "source": "Twitter", "engagement": 189, "country": "United States"},
        {"text": "Tried three different herbal toothpastes. The whitening claims are completely overblown — zero difference after 6 weeks.", "source": "Reviews", "engagement": 234, "country": "United Kingdom"},
        {"text": "Finally found a fluoride-free toothpaste that doesn't feel like brushing with chalk. The charcoal + neem combo is brilliant.", "source": "Reddit", "engagement": 145, "country": "Canada"},
        {"text": "My dentist actually warned me against herbal-only toothpaste. Said fluoride is essential for cavity prevention. Conflicted now.", "source": "Reddit", "engagement": 567, "country": "United States"},
        {"text": "Love the natural ingredients but the gritty texture takes getting used to. My kids refuse to use it though.", "source": "Reviews", "engagement": 78, "country": "Australia"},
        {"text": "Ayurvedic toothpaste has been used for centuries. Why do we trust synthetic chemicals more than proven traditional remedies?", "source": "Blogs", "engagement": 203, "country": "India"},
        {"text": "Switched the whole family to herbal toothpaste. Works great for adults but finding kid-friendly herbal options is genuinely hard.", "source": "Twitter", "engagement": 94, "country": "United Kingdom"},
        {"text": "The price difference is insane. Herbal toothpastes cost 3x more for the same volume. Companies exploiting the natural trend.", "source": "Reddit", "engagement": 445, "country": "United States"},
        {"text": "After reading about microplastics in conventional toothpaste I made the switch. No regrets. Teeth feel just as clean.", "source": "YouTube", "engagement": 2341, "country": "Germany"},
        {"text": "Neem toothpaste has a strong bitter taste that I actually love now. Feels medicinal in a good way.", "source": "Reviews", "engagement": 67, "country": "India"},
        {"text": "My herbal toothpaste left white residue on my electric toothbrush. Minor annoyance but the clean feeling is worth it.", "source": "Reviews", "engagement": 32, "country": "Canada"},
        {"text": "Why isn't herbal toothpaste more mainstream? Every ingredient in my old toothpaste was a chemical I couldn't pronounce.", "source": "Twitter", "engagement": 512, "country": "United States"},
        {"text": "As a periodontist I see patients switching to herbal toothpaste. Some are fine, but please don't skip fluoride if you're cavity-prone.", "source": "Blogs", "engagement": 1203, "country": "United Kingdom"},
        {"text": "The packaging on herbal toothpastes is so much better. Sustainable, recyclable, just thoughtfully designed.", "source": "Twitter", "engagement": 88, "country": "Australia"},
        {"text": "Herbal toothpaste completely fixed my sensitive gums issue. Dentist was surprised at my last checkup.", "source": "Reviews", "engagement": 156, "country": "UAE"},
        {"text": "Tried the trending oil pulling alongside herbal toothpaste. My whole oral care routine feels intentional and natural now.", "source": "Instagram", "engagement": 891, "country": "India"},
        {"text": "Disappointed — the natural toothpaste dried out fast and the pump dispenser clogged within a month.", "source": "Reviews", "engagement": 234, "country": "United States"},
        {"text": "Gen Z is driving the herbal oral care market. We want transparency in ingredients and don't trust legacy brands anymore.", "source": "Blogs", "engagement": 678, "country": "United States"},
        {"text": "Mixed feelings. Herbal toothpaste feels gentler but I had two cavities this year after years with none. Coincidence? Maybe not.", "source": "Reddit", "engagement": 789, "country": "Canada"},
        {"text": "The lack of clinical evidence for most herbal toothpaste brands is concerning. Marketing is ahead of the science.", "source": "Twitter", "engagement": 345, "country": "United Kingdom"},
        {"text": "My teen daughter only uses herbal toothpaste now. She researched ingredients herself. Proud parent moment honestly.", "source": "Reddit", "engagement": 123, "country": "South Africa"},
        {"text": "Herbal mouthwash + herbal toothpaste combo transformed my morning routine. Feel so much better about what goes in my mouth.", "source": "YouTube", "engagement": 1456, "country": "India"},
        {"text": "Some herbal brands are just greenwashing. Check the labels — many still have SLS and artificial flavors buried in there.", "source": "Reddit", "engagement": 892, "country": "United States"},
        {"text": "Started using clove oil toothpaste for toothache. The numbing effect is real and the taste is intense but effective.", "source": "Reviews", "engagement": 203, "country": "India"},
        {"text": "Oral care is such a personal thing. I respect herbal choices but after a root canal I'm sticking to fluoride.", "source": "Twitter", "engagement": 267, "country": "Australia"},
        {"text": "Just launched our herbal toothpaste review series. Tested 12 brands — results are surprising. Link in bio.", "source": "Instagram", "engagement": 3421, "country": "United States"},
        {"text": "The whitening ingredients in herbal toothpastes like baking soda and charcoal can be abrasive long-term. Use sparingly.", "source": "Blogs", "engagement": 567, "country": "Germany"},
        {"text": "Bamboo charcoal toothpaste became my go-to after seeing it trending. Genuinely surprised by how well it cleans.", "source": "Instagram", "engagement": 924, "country": "South Korea"},
        {"text": "My grandmother swore by neem twigs. Now I use neem toothpaste. Full circle moment for my oral care routine.", "source": "Twitter", "engagement": 412, "country": "India"},
        {"text": "Fluoride debate is exhausting. At the end of the day follow your dentist's advice, not social media influencers.", "source": "Reddit", "engagement": 893, "country": "United Kingdom"},
        {"text": "Tried Ayurvedic toothpaste imported from India. Fantastic for fresh breath but my gums bled slightly initially.", "source": "Reviews", "engagement": 178, "country": "UAE"},
        {"text": "Found a kids herbal toothpaste with mild mint and no fluoride — my 5-year-old loves it. Finally a good option.", "source": "Reddit", "engagement": 445, "country": "Canada"},
        {"text": "The herbal oral care category is growing 30% YoY in our market. Consumer shift is very real and accelerating.", "source": "Blogs", "engagement": 1120, "country": "India"},
        {"text": "I work in a pharmacy and herbal toothpaste is now our top-selling oral care SKU. Customers specifically ask for it.", "source": "Reddit", "engagement": 567, "country": "South Africa"},
        {"text": "Meswak toothpaste has been a staple here for decades. Western brands are only now catching on to natural oral care.", "source": "Twitter", "engagement": 334, "country": "UAE"},
        {"text": "My allergist recommended switching to a SLS-free herbal toothpaste due to mouth ulcers. Completely resolved in 3 weeks.", "source": "Reviews", "engagement": 289, "country": "Australia"},
        {"text": "Coconut oil toothpaste is great for sensitivity. Way gentler than whitening formulas and my enamel feels protected.", "source": "YouTube", "engagement": 1834, "country": "United States"},
        {"text": "Herbal toothpastes need better clinical trials before I trust them over fluoride products. Until then I'm unconvinced.", "source": "Blogs", "engagement": 723, "country": "Germany"},
        {"text": "Switched after my hygienist suggested a gentler alternative for my receding gums. Herbal was the obvious choice.", "source": "Reviews", "engagement": 401, "country": "United Kingdom"},
        {"text": "The aftertaste of herbal toothpaste grew on me. Now regular mint toothpaste tastes fake and overpowering.", "source": "Reddit", "engagement": 612, "country": "United States"},
        {"text": "Bought a herbal toothpaste subscription box. Getting 4 different brands to compare — will post results next month.", "source": "Instagram", "engagement": 2103, "country": "Canada"},
        {"text": "My colleague uses herbal toothpaste and has never had a cavity in 10 years. I know correlation isn't causation but still.", "source": "Twitter", "engagement": 334, "country": "South Africa"},
        {"text": "Natural oral care is booming in our region. Ayurvedic brands from India are now in mainstream supermarkets.", "source": "Blogs", "engagement": 982, "country": "UAE"},
        {"text": "Charcoal toothpaste stains my white sink every morning. Great product but the mess is genuinely frustrating.", "source": "Reviews", "engagement": 257, "country": "Australia"},
    ],
    "skincare": [
        {"text": "My dermatologist recommended hyaluronic acid serum over heavy moisturizers for my combination skin. Life changing honestly.", "source": "Reddit", "engagement": 423, "country": "United States"},
        {"text": "Retinol ruined my skin barrier for 6 months. Now I use bakuchiol — same results, none of the irritation. Natural alternatives work.", "source": "Twitter", "engagement": 567, "country": "United Kingdom"},
        {"text": "SPF 50 every day even indoors. People think I'm obsessed but my skin at 35 looks better than it did at 25.", "source": "Instagram", "engagement": 2341, "country": "South Korea"},
        {"text": "The skincare industry pushes so many unnecessary products. You really just need a cleanser, moisturizer, and SPF.", "source": "Reddit", "engagement": 1234, "country": "United States"},
        {"text": "Niacinamide cleared my hyperpigmentation in 8 weeks. Cheap, effective, backed by science. Why did it take me so long to try this.", "source": "YouTube", "engagement": 4512, "country": "India"},
        {"text": "Natural skincare brands are amazing until they start going rancid in the bottle. Preservatives exist for a reason.", "source": "Reddit", "engagement": 789, "country": "Australia"},
        {"text": "Finally found a moisturizer that doesn't pill under makeup. Game changer for my morning routine.", "source": "Reviews", "engagement": 234, "country": "United States"},
        {"text": "Ceramide-based products have completely fixed my damaged skin barrier. Wish I'd known about this years ago.", "source": "Blogs", "engagement": 456, "country": "Germany"},
        {"text": "The 10-step Korean skincare routine is not sustainable for most people. Simplified to 4 steps and my skin is better than ever.", "source": "Twitter", "engagement": 892, "country": "United Kingdom"},
        {"text": "Vitamin C serums are trending but most people don't know they degrade rapidly. Keep them refrigerated or they're useless.", "source": "Blogs", "engagement": 1203, "country": "United States"},
        {"text": "Been using sunflower oil as a moisturizer for 6 months. My skin loves it and it costs nothing. Don't believe the hype.", "source": "Reddit", "engagement": 567, "country": "Canada"},
        {"text": "Peptides are the most underrated skincare ingredient. Better collagen support than most luxury creams I've tried.", "source": "YouTube", "engagement": 3241, "country": "Germany"},
        {"text": "Sensitive skin people — please patch test EVERYTHING. I had a severe reaction to a clean beauty product with essential oils.", "source": "Twitter", "engagement": 2134, "country": "Australia"},
        {"text": "The clean beauty movement has good intentions but natural doesn't mean safe. Poison ivy is natural too.", "source": "Reddit", "engagement": 1567, "country": "United States"},
        {"text": "Found my holy grail moisturizer after years of searching. Works for dry skin, non-comedogenic, fragrance-free.", "source": "Reddit", "engagement": 892, "country": "United Kingdom"},
        {"text": "Azelaic acid is doing what retinol couldn't for my rosacea-prone skin. Gentle, brightening, and anti-inflammatory.", "source": "Reviews", "engagement": 345, "country": "Canada"},
        {"text": "Skincare influencers pushing $200 serums when drugstore equivalents exist with identical ingredients is criminal.", "source": "Twitter", "engagement": 3421, "country": "United States"},
        {"text": "After switching to a gentle fragrance-free routine my skin stopped being oily. Stripping skin makes it produce more oil.", "source": "Blogs", "engagement": 2341, "country": "South Korea"},
        {"text": "Mushroom extracts in skincare is the next big thing. Beta-glucan is deeply moisturizing and chaga has incredible antioxidant properties.", "source": "Instagram", "engagement": 1234, "country": "United States"},
        {"text": "My 60 year old mom started using a basic peptide cream and people ask if she's had work done. Consistency beats expensive treatments.", "source": "Reddit", "engagement": 4512, "country": "India"},
        {"text": "Disappointed with the luxury moisturizer I splurged on. Same ingredients as my $8 drugstore option just nicer packaging.", "source": "Reviews", "engagement": 567, "country": "UAE"},
        {"text": "Barrier repair is all anyone talks about in skincare right now. And honestly for good reason — most of us have damaged ours.", "source": "Blogs", "engagement": 789, "country": "United Kingdom"},
        {"text": "Men's skincare market is finally growing up. Basic SPF and moisturizer is now mainstream. Took long enough.", "source": "Twitter", "engagement": 423, "country": "Germany"},
        {"text": "Probiotic skincare sounds like pseudoscience but there's emerging research on the skin microbiome that's actually compelling.", "source": "Reddit", "engagement": 1023, "country": "United States"},
        {"text": "The amount of microplastics in face scrubs is horrifying. Switched to enzyme exfoliants and never going back.", "source": "YouTube", "engagement": 2134, "country": "Australia"},
        {"text": "Ingredient layering order matters so much. Applying vitamin C and niacinamide together can cancel both out.", "source": "Blogs", "engagement": 3421, "country": "South Korea"},
        {"text": "Snail mucin is weird but I don't care — my skin has never been more hydrated. Korean beauty wins again.", "source": "Instagram", "engagement": 5612, "country": "United States"},
        {"text": "Can we talk about how sunscreen is still not normalized for men? SPF is literally the most evidence-backed anti-aging tool.", "source": "Twitter", "engagement": 1892, "country": "India"},
        {"text": "Glycolic acid toner has transformed my texture. Even skin tone, smaller pores, smoother surface after 6 weeks of use.", "source": "Reviews", "engagement": 712, "country": "Canada"},
        {"text": "Collagen supplements alongside topical peptides — the combo approach is what finally worked for my skin firmness concerns.", "source": "Instagram", "engagement": 1678, "country": "UAE"},
        {"text": "Cloud 9 moisturizer review: overhyped. Nice texture but nothing my basic CeraVe doesn't already do for a fraction of the price.", "source": "YouTube", "engagement": 3210, "country": "United Kingdom"},
        {"text": "Tretinoin changed everything for me. Yes the purge is brutal but after 4 months my skin is unrecognizable.", "source": "Reddit", "engagement": 2890, "country": "United States"},
        {"text": "Centella asiatica is the ingredient my sensitive skin has been waiting for. Calming, repairing, and zero irritation.", "source": "Blogs", "engagement": 934, "country": "South Korea"},
        {"text": "Chemical vs physical sunscreen debate is tiresome. The best one is the one you'll actually use daily.", "source": "Twitter", "engagement": 1567, "country": "Australia"},
        {"text": "My esthetician recommended bakuchiol during pregnancy as a retinol alternative. Safe and genuinely effective.", "source": "Reviews", "engagement": 823, "country": "United States"},
        {"text": "Skincare in my 40s is completely different from my 20s. Hydration and barrier support over actives. Took years to understand this.", "source": "Reddit", "engagement": 1923, "country": "Germany"},
        {"text": "Indian skincare traditions like ubtan and rose water are finally getting the global recognition they deserve.", "source": "Instagram", "engagement": 4231, "country": "India"},
        {"text": "Sunscreen in South Africa is non-negotiable. High UV index year-round. People here take SPF very seriously.", "source": "Reddit", "engagement": 678, "country": "South Africa"},
        {"text": "Niacinamide with zinc is the best combo for acne-prone oily skin. Cheap and you can find it in any drugstore.", "source": "YouTube", "engagement": 3892, "country": "United States"},
        {"text": "The glass skin trend from Korea has inspired me to focus on hydration above all else. Skin looks luminous now.", "source": "Instagram", "engagement": 2134, "country": "South Korea"},
        {"text": "My dark spots from old breakouts faded completely with consistent vitamin C use. Took 4 months but worth it.", "source": "Reviews", "engagement": 512, "country": "South Africa"},
        {"text": "Gua sha and jade rolling are beautiful rituals but the lymphatic drainage claims are largely exaggerated. Do it because it feels good.", "source": "Blogs", "engagement": 1234, "country": "United States"},
        {"text": "Finding moisturizer for extremely dry skin in Canadian winters is genuinely challenging. Nothing lasts through the cold.", "source": "Reddit", "engagement": 445, "country": "Canada"},
        {"text": "Rosewater toner after cleansing has been part of my routine for 20 years. My mother taught me this and it still works.", "source": "Reviews", "engagement": 612, "country": "UAE"},
        {"text": "Medical grade skincare vs luxury brands — the dermatologist-recommended options consistently outperform in independent testing.", "source": "Blogs", "engagement": 2341, "country": "United Kingdom"},
    ],
    "beverages": [
        {"text": "Zero sugar energy drinks are everywhere now but the artificial sweetener aftertaste is still awful. Need better alternatives.", "source": "Reddit", "engagement": 423, "country": "United States"},
        {"text": "Switched from regular soda to sparkling water 6 months ago. Cravings for sweet drinks completely gone.", "source": "Twitter", "engagement": 892, "country": "United Kingdom"},
        {"text": "The stevia aftertaste in most sugar-free drinks is a dealbreaker for me. Monk fruit sweetened options are so much better.", "source": "Reviews", "engagement": 234, "country": "Canada"},
        {"text": "Kombucha is the only functional beverage that actually delivers on its promise. 2 years of daily drinking, gut health noticeably improved.", "source": "Reddit", "engagement": 1203, "country": "Australia"},
        {"text": "Sugar-free doesn't mean healthy. Artificial sweeteners still spike insulin and mess with gut bacteria according to recent research.", "source": "Blogs", "engagement": 2341, "country": "United States"},
        {"text": "Electrolyte drinks without sugar are a godsend for endurance athletes. LMNT changed my performance metrics dramatically.", "source": "YouTube", "engagement": 3412, "country": "United States"},
        {"text": "Why do all protein shakes taste like plastic? The texture is always wrong too. Huge gap in the market for a genuinely good tasting one.", "source": "Reddit", "engagement": 567, "country": "United Kingdom"},
        {"text": "My doctor told me to cut sugar so I explored sugar-free options. Honestly most of them taste better now.", "source": "Twitter", "engagement": 345, "country": "Germany"},
        {"text": "Energy drink brands targeting teens with 200mg caffeine and zero nutritional value is genuinely irresponsible.", "source": "Blogs", "engagement": 1892, "country": "United Kingdom"},
        {"text": "The functional beverage market is booming — adaptogens, nootropics, collagen. People are drinking their supplements now.", "source": "Instagram", "engagement": 4231, "country": "United States"},
        {"text": "Tried 8 different sugar-free protein shakes. Only 2 were actually drinkable. The rest tasted like sweetened chalk.", "source": "YouTube", "engagement": 2341, "country": "Canada"},
        {"text": "Infused water is genuinely underrated. Cucumber mint water completely replaced my need for sweet drinks.", "source": "Reddit", "engagement": 567, "country": "India"},
        {"text": "The health halo around sports drinks is marketing nonsense. Unless you're exercising 90+ minutes you don't need electrolytes.", "source": "Twitter", "engagement": 1234, "country": "Australia"},
        {"text": "Mushroom coffee is trending and I'm here for it. Half the caffeine, adaptogens included, better sustained energy without the crash.", "source": "Instagram", "engagement": 3421, "country": "United States"},
        {"text": "Probiotic sodas are the most exciting thing in beverages right now. Gut health benefits + carbonation + no sugar.", "source": "Reddit", "engagement": 892, "country": "Germany"},
        {"text": "My kids refuse sugar-free anything. The sweetener taste is too strong for children's palates apparently.", "source": "Twitter", "engagement": 234, "country": "United Kingdom"},
        {"text": "Cold brew coffee without sugar is genuinely one of life's great pleasures. Smooth, no bitterness, high caffeine. Perfect.", "source": "YouTube", "engagement": 5612, "country": "United States"},
        {"text": "The zero sugar label on drinks is misleading when there's still 25g of carbs from other sources. Regulation is needed.", "source": "Blogs", "engagement": 1023, "country": "Canada"},
        {"text": "Hydration is the most underrated health hack. Since tracking my water intake everything improved — sleep, skin, energy, focus.", "source": "Instagram", "engagement": 7823, "country": "India"},
        {"text": "Plant-based protein drinks are finally catching up in taste. Pea protein has come a long way from 3 years ago.", "source": "Reviews", "engagement": 456, "country": "Australia"},
        {"text": "The price gap between sugar beverages and healthy alternatives needs to close. Health shouldn't be a luxury.", "source": "Twitter", "engagement": 1567, "country": "South Africa"},
        {"text": "Matcha latte with oat milk, no sugar. This is the drink that replaced my daily cappuccino and I feel so much better.", "source": "Reddit", "engagement": 2134, "country": "South Korea"},
        {"text": "Collagen drinks are everywhere. The bioavailability questions are real though — does oral collagen actually reach your skin?", "source": "Blogs", "engagement": 892, "country": "United States"},
        {"text": "Wellness beverages are genuinely helping people make healthier choices. Don't dismiss the trend — it's moving the needle.", "source": "Instagram", "engagement": 3241, "country": "United Kingdom"},
        {"text": "Sparkling water with natural fruit essence satisfies my carbonation craving without any sweeteners. Simple solution.", "source": "Reviews", "engagement": 178, "country": "UAE"},
        {"text": "The sugar tax worked. Beverage companies reformulated products and consumer health outcomes improved. Policy matters.", "source": "Blogs", "engagement": 2341, "country": "United Kingdom"},
        {"text": "Lassi and chaas are the original probiotic drinks and Indians have been drinking them for millennia. No need for imported kombucha.", "source": "Reddit", "engagement": 1892, "country": "India"},
        {"text": "Coconut water as a post-workout drink is criminally underrated. Natural electrolytes, low calorie, great taste.", "source": "Twitter", "engagement": 1456, "country": "India"},
        {"text": "Green tea consumption in our country is cultural. The West is now discovering what we have known for centuries.", "source": "Blogs", "engagement": 2103, "country": "South Korea"},
        {"text": "Rooibos tea is our local superfood. No caffeine, loads of antioxidants, and it's uniquely South African.", "source": "Reddit", "engagement": 934, "country": "South Africa"},
        {"text": "Karak chai with no sugar is actually an acquired taste I'm starting to appreciate. Good alternative to milky sweet tea.", "source": "Twitter", "engagement": 612, "country": "UAE"},
        {"text": "Oat milk in beverages has overtaken almond milk in our sales. Environmental awareness is driving the switch.", "source": "Blogs", "engagement": 1678, "country": "Germany"},
        {"text": "Switched our whole office to sparkling water dispensers. Productivity improved and plastic waste dropped dramatically.", "source": "Instagram", "engagement": 2891, "country": "Australia"},
        {"text": "Pre-workout drinks with 300mg caffeine are irresponsible products. Heart palpitations shouldn't be a normal workout side effect.", "source": "Reddit", "engagement": 3421, "country": "Canada"},
        {"text": "The craft non-alcoholic beverage scene is incredible right now. Bartenders putting real thought into zero-proof cocktails.", "source": "Twitter", "engagement": 2134, "country": "United States"},
        {"text": "Immunity-boosting drinks with turmeric and ginger exploded during the pandemic and honestly never lost steam.", "source": "YouTube", "engagement": 4512, "country": "India"},
        {"text": "Yerba mate is a sleeper hit in the functional beverage market. High caffeine, antioxidants, and a unique social drinking culture.", "source": "Reddit", "engagement": 1234, "country": "United States"},
        {"text": "My teenage son drinks 3 energy drinks a day. As a parent I'm deeply concerned and there's no regulation protecting us.", "source": "Blogs", "engagement": 2341, "country": "South Africa"},
        {"text": "Hibiscus tea cold-brewed overnight. Tart, refreshing, beautiful colour and packed with antioxidants. My summer drink.", "source": "Instagram", "engagement": 3892, "country": "UAE"},
        {"text": "Canned sparkling water market in Germany grew 40% this year. People are actively choosing health over habit.", "source": "Blogs", "engagement": 1456, "country": "Germany"},
    ],
    "wellness": [
        {"text": "Ashwagandha genuinely helped my cortisol levels. Blood test confirmed it. Adaptogens aren't pseudoscience after all.", "source": "Reddit", "engagement": 1234, "country": "United States"},
        {"text": "The supplement industry is largely unregulated. Half of what's on shelves doesn't contain what the label says.", "source": "Blogs", "engagement": 2341, "country": "United Kingdom"},
        {"text": "Magnesium glycinate for sleep is the most underrated supplement. Cheap, effective, no dependency.", "source": "Twitter", "engagement": 3421, "country": "United States"},
        {"text": "Started taking vitamin D + K2 combo. My SAD symptoms improved significantly over the winter.", "source": "Reddit", "engagement": 892, "country": "Canada"},
        {"text": "Probiotics changed my digestion completely. Took 8 weeks to see results but the change is undeniable.", "source": "Reviews", "engagement": 567, "country": "Australia"},
        {"text": "Collagen supplements are the biggest wellness grift. The molecule is too large to absorb intact.", "source": "Blogs", "engagement": 1892, "country": "Germany"},
        {"text": "Omega-3 from whole fish vs supplement form — bioavailability difference is significant according to my nutrition research.", "source": "Reddit", "engagement": 456, "country": "United Kingdom"},
        {"text": "Lion's mane mushroom has measurably improved my focus and recall. I was skeptical but the research is actually solid.", "source": "YouTube", "engagement": 4512, "country": "United States"},
        {"text": "My doctor told me I was wasting money on a 12-supplement stack. Bloodwork showed I only needed D3 and B12.", "source": "Twitter", "engagement": 2134, "country": "Canada"},
        {"text": "The wellness industry targets anxiety. They profit from making healthy people feel like they need to optimize everything.", "source": "Reddit", "engagement": 3421, "country": "United States"},
        {"text": "Creatine is the most scientifically validated supplement and it costs almost nothing. Why do people still avoid it?", "source": "YouTube", "engagement": 6234, "country": "Australia"},
        {"text": "Turmeric with black pepper for inflammation. Stopped taking ibuprofen daily after adding this to my routine.", "source": "Reviews", "engagement": 345, "country": "India"},
        {"text": "Third-party tested supplements are the only ones worth buying. NSF and Informed Sport certifications matter enormously.", "source": "Blogs", "engagement": 1023, "country": "United States"},
        {"text": "Berberine is being called nature's metformin for blood sugar management. Clinical evidence is surprisingly strong.", "source": "Reddit", "engagement": 2341, "country": "United Kingdom"},
        {"text": "The sleep supplement market is exploding — melatonin, magnesium, L-theanine, glycine. People are prioritizing sleep finally.", "source": "Instagram", "engagement": 4231, "country": "United States"},
        {"text": "Protein intake is the most impactful nutrition lever most people ignore. Getting adequate protein should precede any supplementation.", "source": "YouTube", "engagement": 5612, "country": "Canada"},
        {"text": "Wellness supplements are increasingly marketed to men. The stigma around men caring for their health is finally dissolving.", "source": "Twitter", "engagement": 892, "country": "United Kingdom"},
        {"text": "NAD+ precursors for longevity is the newest trend. NMN vs NR debate is fascinating but evidence is still preliminary.", "source": "Blogs", "engagement": 1567, "country": "United States"},
        {"text": "Kids gummy vitamins have more sugar than candy. The wellness industry infantilizing adult supplements is a problem.", "source": "Reddit", "engagement": 2134, "country": "Australia"},
        {"text": "Spent $300 a month on supplements. Stopped everything for 6 months. Felt the same. Now I take 3 evidence-based ones only.", "source": "Reddit", "engagement": 4512, "country": "United States"},
        {"text": "Personalized nutrition based on microbiome testing is the future. Generic supplement advice is too blunt an instrument.", "source": "Instagram", "engagement": 3241, "country": "Germany"},
        {"text": "Electrolyte supplements during Ramadan have been life-changing for fasting endurance. Practical wellness solution.", "source": "Twitter", "engagement": 678, "country": "UAE"},
        {"text": "The placebo effect in wellness is underestimated. But if it works and it's harmless, does the mechanism actually matter?", "source": "Reddit", "engagement": 1892, "country": "United States"},
        {"text": "Hormone health supplements for women are booming. Perimenopause support is finally getting mainstream attention.", "source": "Instagram", "engagement": 5612, "country": "United Kingdom"},
        {"text": "B12 deficiency is wildly common in vegans and is causing real neurological issues. Supplement non-negotiably if plant-based.", "source": "Blogs", "engagement": 2341, "country": "Canada"},
        {"text": "Gut-brain axis research is the most exciting thing in health science. Prebiotics and probiotics may be mental health tools.", "source": "YouTube", "engagement": 7823, "country": "United States"},
        {"text": "Chyawanprash has been an immune booster in our household for generations. Traditional Ayurvedic wellness actually works.", "source": "Reviews", "engagement": 892, "country": "India"},
        {"text": "Moringa is called a superfood in our region and has been used in cooking for centuries. No need to import foreign supplements.", "source": "Blogs", "engagement": 1234, "country": "South Africa"},
        {"text": "Zinc supplementation during flu season genuinely reduced my sick days this year. Simple, cheap, effective.", "source": "Reddit", "engagement": 1456, "country": "Germany"},
        {"text": "Quercetin with bromelain is my new antihistamine alternative. No drowsiness, natural, and it actually works for my allergies.", "source": "Twitter", "engagement": 934, "country": "Australia"},
        {"text": "Iron deficiency is so underdiagnosed in women. My fatigue for years was just low iron. A simple blood test changed my life.", "source": "Instagram", "engagement": 5102, "country": "United Kingdom"},
        {"text": "Saffron extract for mood support has proper clinical backing now. One of the most interesting natural compounds in research.", "source": "Blogs", "engagement": 1678, "country": "UAE"},
        {"text": "Vitamin D deficiency in our northern climate is almost universal. D3 supplementation should be a public health priority.", "source": "Reddit", "engagement": 2341, "country": "Canada"},
        {"text": "Colostrum supplements are having a moment. Gut healing and immune support with solid science behind it.", "source": "Instagram", "engagement": 3421, "country": "United States"},
        {"text": "Triphala is a complete digestive support system used in Ayurveda for thousands of years. Still relevant and still effective.", "source": "Reviews", "engagement": 712, "country": "India"},
        {"text": "Spirulina tastes awful but I have genuinely more energy since adding it to my smoothies. Worth pushing through the taste.", "source": "YouTube", "engagement": 2891, "country": "South Africa"},
        {"text": "The wellness industry is starting to serve older adults meaningfully. Supplements targeting joint health and cognition are finally improving.", "source": "Blogs", "engagement": 1567, "country": "Germany"},
        {"text": "Hydrolysed collagen in my morning coffee has become a non-negotiable. Joints feel better and skin is visibly more plump.", "source": "Twitter", "engagement": 2103, "country": "Australia"},
        {"text": "Fenugreek for blood sugar management. My diabetic father has seen measurable improvement as a complementary approach alongside medication.", "source": "Reddit", "engagement": 1892, "country": "India"},
        {"text": "Black seed oil is deeply embedded in our wellness culture. The Western world is only now validating what we have long known.", "source": "Reviews", "engagement": 1234, "country": "UAE"},
    ],
    "haircare": [
        {"text": "Sulphate-free shampoo took 6 weeks to adjust to. First month hair felt weird. Now it's the only thing I'll use.", "source": "Reddit", "engagement": 567, "country": "United States"},
        {"text": "Hair loss at 28 sent me down a rabbit hole. Minoxidil works but the finasteride decision is complicated and personal.", "source": "Reddit", "engagement": 1234, "country": "United Kingdom"},
        {"text": "Castor oil for hair growth is mostly myth. The few studies that exist are tiny and low quality. Save your money.", "source": "Blogs", "engagement": 892, "country": "Canada"},
        {"text": "Scalp health is the root cause of most hair issues. Nobody talks about this enough. Focus on scalp, hair follows.", "source": "YouTube", "engagement": 3421, "country": "United States"},
        {"text": "Rice water rinse for hair strength — been doing this for 3 months. My stylist noticed a real difference in hair texture.", "source": "Instagram", "engagement": 2341, "country": "South Korea"},
        {"text": "Hair porosity matters more than any ingredient. Understanding your hair's porosity unlocks what products will actually work.", "source": "Twitter", "engagement": 1567, "country": "United States"},
        {"text": "Protein overload is real. Too many protein treatments made my hair brittle and caused breakage. Balance is everything.", "source": "Reviews", "engagement": 456, "country": "Australia"},
        {"text": "Natural hair community has the best advice on moisture retention. Techniques developed for curly hair work for everyone.", "source": "Reddit", "engagement": 892, "country": "South Africa"},
        {"text": "Biotin supplements did nothing for my hair. Iron deficiency was the actual culprit. Get bloodwork before buying supplements.", "source": "Twitter", "engagement": 2134, "country": "United Kingdom"},
        {"text": "The no-poo method genuinely doesn't work for everyone. If you have an oily scalp you need actual cleansing.", "source": "Blogs", "engagement": 1023, "country": "United States"},
        {"text": "Found a shampoo bar that replaced my plastic bottle routine. Zero waste, works amazingly, and my hair is healthier.", "source": "Instagram", "engagement": 4512, "country": "Germany"},
        {"text": "Keratin treatment gave me silky hair for 4 months. But the formaldehyde risk is real and the cost every 4 months adds up.", "source": "YouTube", "engagement": 2341, "country": "United States"},
        {"text": "DHT blocking shampoos are trending for hair loss. Clinical evidence is modest but anecdotally many people swear by them.", "source": "Reddit", "engagement": 1892, "country": "Canada"},
        {"text": "My hairstylist said heat protectant is non-negotiable. I ignored her for years. I now have heat damage I'm growing out.", "source": "Twitter", "engagement": 892, "country": "Australia"},
        {"text": "Olaplex actually works. Chemist comparison vs. the expensive salon version showed identical active ingredients.", "source": "Blogs", "engagement": 3421, "country": "United Kingdom"},
        {"text": "Postpartum hair loss is devastating and nobody warns you. Support communities online made me feel less alone.", "source": "Reddit", "engagement": 5612, "country": "United States"},
        {"text": "Traditional hair oiling practices from India are getting mainstream recognition. Grandmothers were right all along.", "source": "Instagram", "engagement": 4231, "country": "India"},
        {"text": "My 4C hair finally thriving after finding the right routine. It took years and hundreds of dollars of trial and error.", "source": "YouTube", "engagement": 6234, "country": "South Africa"},
        {"text": "Scalp massage for 4 minutes daily — been consistent for 6 months and baby hairs are visibly growing. Circulation matters.", "source": "Twitter", "engagement": 1567, "country": "India"},
        {"text": "Affordable drugstore shampoos often outperform expensive salon brands. Check the active ingredients, not the packaging.", "source": "Blogs", "engagement": 2134, "country": "Canada"},
        {"text": "Dry shampoo dependency is damaging scalps. Products that mask grease are not the same as washing your hair.", "source": "Reddit", "engagement": 1892, "country": "United States"},
        {"text": "The gendered pricing of hair products is infuriating. Men and women paying wildly different prices for identical formulas.", "source": "Twitter", "engagement": 3421, "country": "Germany"},
        {"text": "Rosemary oil for hair growth has actual research behind it. Comparable to minoxidil in one study. I'm convinced.", "source": "Instagram", "engagement": 7823, "country": "United States"},
        {"text": "Detangling natural hair correctly has saved me so much breakage. Finger detangle before any tool, always on wet conditioned hair.", "source": "YouTube", "engagement": 4512, "country": "South Africa"},
        {"text": "Amla oil is the secret my Indian relatives have known forever. Hair growth, strength, and shine that no western product matches.", "source": "Reddit", "engagement": 2341, "country": "India"},
        {"text": "Onion juice for hair growth — I smell terrible for a few hours but the regrowth I've seen is genuinely hard to argue with.", "source": "YouTube", "engagement": 5102, "country": "India"},
        {"text": "Korean hair care philosophy focuses on scalp care first. Products are layered like a skincare routine. Game changing approach.", "source": "Blogs", "engagement": 3421, "country": "South Korea"},
        {"text": "My hair finally stopped breaking after switching to a satin pillowcase. Such a simple change with remarkable results.", "source": "Instagram", "engagement": 2891, "country": "UAE"},
        {"text": "Baobab oil for hair moisture is the underrated African beauty secret that deserves global recognition.", "source": "Twitter", "engagement": 1567, "country": "South Africa"},
        {"text": "Low-porosity hair needs heat to absorb moisture properly. Once I understood this my entire routine changed.", "source": "Reddit", "engagement": 2103, "country": "United States"},
        {"text": "Argan oil made my hair greasy. Jojoba oil was the perfect lightweight alternative that my fine hair could actually handle.", "source": "Reviews", "engagement": 712, "country": "Canada"},
        {"text": "Hair breakage in dry desert climates is a constant battle. Deep conditioning weekly is non-negotiable where I live.", "source": "Reddit", "engagement": 934, "country": "UAE"},
        {"text": "Finally found a shampoo that works in hard water. Water quality affects hair health more than people realise.", "source": "Reviews", "engagement": 1234, "country": "United Kingdom"},
        {"text": "Inversion method for hair growth — hanging upside down to boost scalp circulation. Feels ridiculous but I'm seeing results.", "source": "Instagram", "engagement": 3892, "country": "Australia"},
        {"text": "Bond repair treatments like Olaplex and K18 are worth every cent if you colour or heat style. Structural repair is real.", "source": "Blogs", "engagement": 2456, "country": "Germany"},
        {"text": "Hair loss running in my family on both sides. Started preventive care at 23. Early intervention genuinely changes the outcome.", "source": "Reddit", "engagement": 1892, "country": "United States"},
        {"text": "Protective styles have transformed my hair health. Braids and twists mean less manipulation and dramatically less breakage.", "source": "YouTube", "engagement": 5612, "country": "South Africa"},
        {"text": "My husband finally started using conditioner after 40 years. Men's hair care is decades behind women's in terms of routine.", "source": "Twitter", "engagement": 2341, "country": "United Kingdom"},
        {"text": "Neem oil shampoo solved my dandruff after years of medicated shampoos failing. Traditional remedies sometimes win.", "source": "Reviews", "engagement": 892, "country": "India"},
        {"text": "The curl pattern spectrum needs better representation in hair care products. Not everyone fits the 3 main categories.", "source": "Blogs", "engagement": 3102, "country": "United States"},
    ],
}

_CATEGORY_MAP = {
    "oral care": "oral care", "toothpaste": "oral care", "fluoride": "oral care",
    "neem": "oral care", "dental": "oral care", "whitening": "oral care",
    "skincare": "skincare", "moisturizer": "skincare", "serum": "skincare",
    "sunscreen": "skincare", "retinol": "skincare", "spf": "skincare",
    "beverage": "beverages", "drink": "beverages", "sugar": "beverages",
    "kombucha": "beverages", "energy drink": "beverages", "protein shake": "beverages",
    "wellness": "wellness", "supplement": "wellness", "vitamin": "wellness",
    "probiotic": "wellness", "adaptogen": "wellness", "ashwagandha": "wellness",
    "haircare": "haircare", "hair": "haircare", "shampoo": "haircare",
    "scalp": "haircare", "conditioner": "haircare",
}


def get_conversations(classification: dict) -> List[Dict]:
    topic = classification.get("topic", "").lower()
    category = classification.get("category", "").lower()
    keywords = [k.lower() for k in classification.get("keywords", [])]

    all_text = " ".join([topic, category] + keywords)
    matched_key = None

    for map_key, data_key in _CATEGORY_MAP.items():
        if map_key in all_text:
            matched_key = data_key
            break

    if not matched_key:
        matched_key = "oral care"

    raw = _RAW[matched_key]
    dates = _spread_dates(len(raw))

    conversations = []
    for i, item in enumerate(raw):
        conversations.append({
            "text": item["text"],
            "source": item["source"],
            "engagement": item["engagement"],
            "country": item["country"],
            "timestamp": dates[i],
        })

    return conversations
